### ISSUE TITLE
いいですね．

### ISSUE THREAD

**Issue by daddygongon** [TowaInoue-kg/RenameDatasets#1]
こういうのめちゃくちゃよく使います．いい筋ですね．
ただ，
> new_name = "#{index + 1}_#{base_name}#{ext}"

だと，数字から始まるファイル名を許さないOSがあったように思います．
そこで，

> new_name = "d#{index + 1}_#{base_name}.#{ext}"

などとするのがいいとおもます．

shellの補完機能を使ってcatやheadと組み合わせてファイルの中身を確認する作業が単純化できます．
もっと便利に拡張して’Happy coding!!"してください．

**Comment by TowaInoue-kg** [comment]
レビューありがとうございます。
指摘の点変更させていただきました。
もっと便利に拡張していければと思います。
